//===========================================================================
//
// Name:		Harley_c.c
// Function:		Harley Quinn, rank 5
// Programmer:		MrElusive (MrElusive@idsoftware.com), modified by Wrath (wrath@polycount.com)
// version:		1
// Tab Size:		4 (real tabs)
//===========================================================================

#include "chars.h"

skill 1
{
		CHARACTERISTIC_NAME							"Harley"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.35
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/Harley_w.c"
	CHARACTERISTIC_AIM_SKILL					0.15
	CHARACTERISTIC_AIM_ACCURACY					0.15
	CHARACTERISTIC_VIEW_FACTOR					0.45
	CHARACTERISTIC_VIEW_MAXCHANGE				90
	CHARACTERISTIC_REACTIONTIME					3.5

	CHARACTERISTIC_CHAT_FILE					"bots/Harley_t.c"
	CHARACTERISTIC_CHAT_NAME					"Harley"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.9
	CHARACTERISTIC_CHAT_MISC					0.9
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.9
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.9
	CHARACTERISTIC_CHAT_KILL					0.9
	CHARACTERISTIC_CHAT_DEATH					0.9
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.9
	CHARACTERISTIC_CHAT_HITTALKING				0.9
	CHARACTERISTIC_CHAT_HITNODEATH				0.9
	CHARACTERISTIC_CHAT_HITNOKILL				0.9
	CHARACTERISTIC_CHAT_RANDOM					0.9
	CHARACTERISTIC_CHAT_REPLY					0.9

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.9
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_GRAPPLE_USER					0.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/Harley_i.c"
	CHARACTERISTIC_AGGRESSION					0.9
	CHARACTERISTIC_SELFPRESERVATION				0.45
	CHARACTERISTIC_VENGEFULNESS					0.9
	CHARACTERISTIC_CAMPER						0.25

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5
}

skill 4
{
	CHARACTERISTIC_NAME							"Harley"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/Harley_w.c"
	CHARACTERISTIC_AIM_SKILL					0.35
	CHARACTERISTIC_AIM_ACCURACY					0.35
	CHARACTERISTIC_VIEW_FACTOR					0.45
	CHARACTERISTIC_VIEW_MAXCHANGE				120
	CHARACTERISTIC_REACTIONTIME					2.5

	CHARACTERISTIC_CHAT_FILE					"bots/Harley_t.c"
	CHARACTERISTIC_CHAT_NAME					"Harley"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.8
	CHARACTERISTIC_CHAT_MISC					0.8
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.8
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.8
	CHARACTERISTIC_CHAT_KILL					0.8
	CHARACTERISTIC_CHAT_DEATH					0.8
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.8
	CHARACTERISTIC_CHAT_HITTALKING				0.8
	CHARACTERISTIC_CHAT_HITNODEATH				0.8
	CHARACTERISTIC_CHAT_HITNOKILL				0.8
	CHARACTERISTIC_CHAT_RANDOM					0.8
	CHARACTERISTIC_CHAT_REPLY					0.8

	CHARACTERISTIC_CROUCHER						0.25
	CHARACTERISTIC_JUMPER						0.9
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_GRAPPLE_USER					0.05

	CHARACTERISTIC_ITEMWEIGHTS					"bots/Harley_i.c"
	CHARACTERISTIC_AGGRESSION					0.9
	CHARACTERISTIC_SELFPRESERVATION				0.45
	CHARACTERISTIC_VENGEFULNESS					0.9
	CHARACTERISTIC_CAMPER						0.25

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5
}

skill 5
{
	CHARACTERISTIC_NAME							"Harley"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					1.0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/Harley_w.c"
	CHARACTERISTIC_AIM_SKILL					1.0
	CHARACTERISTIC_AIM_ACCURACY					1.0
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/Harley_t.c"
	CHARACTERISTIC_CHAT_NAME					"Harley"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.7
	CHARACTERISTIC_CHAT_MISC					0.7
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.7
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.7
	CHARACTERISTIC_CHAT_KILL					0.7
	CHARACTERISTIC_CHAT_DEATH					0.7
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.7
	CHARACTERISTIC_CHAT_HITTALKING				0.7
	CHARACTERISTIC_CHAT_HITNODEATH				0.7
	CHARACTERISTIC_CHAT_HITNOKILL				0.7
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					0.7

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.9
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/Harley_i.c"
	CHARACTERISTIC_AGGRESSION					0.95
	CHARACTERISTIC_SELFPRESERVATION				0.95
	CHARACTERISTIC_VENGEFULNESS					0.95
	CHARACTERISTIC_CAMPER						0.5

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.7
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	1.0
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		1.0
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		1.0
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			1.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			1.0
	CHARACTERISTIC_AIM_SKILL_BFG10K				1.0

	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_EASY_FRAGGER					1.0
	CHARACTERISTIC_ALERTNESS					1.0
}
